codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        informational: false
    patch:
      default:
        target: 100%
        threshold: 0%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
